language: ruby
rvm:
- 2.1
script: bundle exec rake
bundler_args: "--binstubs"
branches:
  only:
  - master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - GH_REF: github.com/usnationalarchives/capstone-grs.git
  - secure: q2DYbWl8SAm1uz9/bgw57AW4CJU9/Th7MALAgbks4Iw1wnJtlkLvrtdPPrZ29nOiyfwHgNdZXXOp1XIFmIlBbUbhtToM3JcXsjsmm2iGSjO3cAR2Dv/Bzt0SxQGsF585JLovJaIDDjT7qlXlwV5MrpWnTkwo2eJbOYLpWn47oNslwsAclZ+CYAfKeyMEHyfCLGxVNssUBno6iTyg4pjDPodmOwOZshzeHI8qfc94jDNG79DSSr13fBokwtCB15VdR1w7ahLqN3BX5eApsZxt5WaDPr4KB4l+AhWWKVu6z79Huwrkfih6xoML/oIFkGXR/3rj5Ry7JUnnOTJcAivTJ9YmeAlX15LirHRwhHNY9A5KG/eJpqnnziQv4KNpQz+FXdalb2BCDISm6Sqn4EBFv9vQJuQ/244DjxTI15icXwFdB7M6iYCn8WZfZwfoc75rQAH7I2bCKIG3NN42vlaTY4IgyPMjZ+kX7xhbSm9iXx5hful6Mk70YzvluTQA6OZC+Le5VhOpOkUEO/RU8YrKXWcsq+BKWgXNOvZJZL+lB36tCe7f26lqJMCr7d3VEi28XGzgkv4paZSKsugN+218+07U55VRxtjrJUdrNdvpbePUrmXKaLZjwRQmMRodCBIlTgrJJNyVdW+jYLV5RZMUNjiaObS2lZshbBw9L4y5eY8=
install:
- git config --global user.email "davidnaffis@gmail.com"
- git config --global user.name "naffis"
- travis_wait bundle install